// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchConvertToWebP(arg1, arg2) {
  return window['go']['app']['App']['BatchConvertToWebP'](arg1, arg2);
}

export function ConvertToWebP(arg1, arg2) {
  return window['go']['app']['App']['ConvertToWebP'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}
