// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BatchConvertToWebP(arg1:Array<models.File>,arg2:string):Promise<void>;

export function ConvertToWebP(arg1:models.File,arg2:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;
