// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWebP() {
  return window['go']['main']['App']['CheckWebP']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallWebP() {
  return window['go']['main']['App']['InstallWebP']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
