// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckWebP():Promise<boolean>;

export function Greet(arg1:main.Person):Promise<string>;

export function InstallWebP():Promise<boolean>;

export function ReadFile(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;
